// <auto-generated />
using DeliverySac.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliverySac.API.Migrations
{
    [DbContext(typeof(DeliverySacDbContext))]
    [Migration("20261007033817_SeedClientes")]
    partial class SeedClientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeliverySac.API.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Calle 1 #100, Centro",
                            Nombre = "Café Central"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Avenida Principal 250, Zona Norte",
                            Nombre = "Restaurante El Buen Sabor"
                        },
                        new
                        {
                            Id = 3,
                            Direccion = "Calle Secundaria 75, Barrio Sur",
                            Nombre = "Farmacia Salud Plus"
                        });
                });

            modelBuilder.Entity("DeliverySac.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@deliverysac.com",
                            PasswordHash = "$2a$11$XLD26bRbc2nvVHlfqvBRPOA7UElBZdAkd/L.MLLWvtEH2jW7W9x0S",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Email = "repartidor@deliverysac.com",
                            PasswordHash = "$2a$11$18C7OK9FvrVP0OkP7Wmn1u8Jk5tYlSj3tj2ulxkkQktN151KcdFdi",
                            Rol = "Repartidor"
                        },
                        new
                        {
                            Id = 3,
                            Email = "supervisor@deliverysac.com",
                            PasswordHash = "$2a$11$WKbwVkdWc7O55FGbHWrWKOXLz1BQaNXGFqwBJmfOQJvwsK52FwFPK",
                            Rol = "Supervisor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
