// <auto-generated />
using DeliverySac.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliverySac.API.Migrations
{
    [DbContext(typeof(DeliverySacDbContext))]
    [Migration("20261007033716_AddClientesTable")]
    partial class AddClientesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeliverySac.API.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("DeliverySac.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@deliverysac.com",
                            PasswordHash = "$2a$11$dgiNYXjWxkFpbuz4LgNG6eUBbKnXVj9RKrm7r/PjIgfuDm1ImPVEO",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Email = "repartidor@deliverysac.com",
                            PasswordHash = "$2a$11$2dIHN0h.64ARsjnPcfAD2OPhJ/bLyLxBK74fneyRB/IfVsysy12Je",
                            Rol = "Repartidor"
                        },
                        new
                        {
                            Id = 3,
                            Email = "supervisor@deliverysac.com",
                            PasswordHash = "$2a$11$hINk/Os4BDBNuYgd13WC5O1uh1qJSx4XCex2X.7KzcC55OIlbK8w.",
                            Rol = "Supervisor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
