// <auto-generated />
using System;
using DeliverySac.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliverySac.API.Migrations
{
    [DbContext(typeof(DeliverySacDbContext))]
    [Migration("20261007035422_SeedCambiosEstado")]
    partial class SeedCambiosEstado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeliverySac.API.Models.Asignacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("RepartidorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("RepartidorId");

                    b.ToTable("Asignaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaAsignacion = new DateTime(2026, 10, 7, 2, 54, 22, 544, DateTimeKind.Utc).AddTicks(5114),
                            PedidoId = 2,
                            RepartidorId = 2
                        },
                        new
                        {
                            Id = 2,
                            FechaAsignacion = new DateTime(2026, 10, 6, 22, 54, 22, 544, DateTimeKind.Utc).AddTicks(5114),
                            PedidoId = 3,
                            RepartidorId = 2
                        });
                });

            modelBuilder.Entity("DeliverySac.API.Models.CambioEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CambiosEstado");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstadoAnterior = 0,
                            EstadoNuevo = 1,
                            Fecha = new DateTime(2026, 10, 7, 2, 54, 22, 544, DateTimeKind.Utc).AddTicks(5157),
                            PedidoId = 2,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            EstadoAnterior = 0,
                            EstadoNuevo = 1,
                            Fecha = new DateTime(2026, 10, 6, 22, 54, 22, 544, DateTimeKind.Utc).AddTicks(5157),
                            PedidoId = 3,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 3,
                            EstadoAnterior = 1,
                            EstadoNuevo = 2,
                            Fecha = new DateTime(2026, 10, 7, 3, 24, 22, 544, DateTimeKind.Utc).AddTicks(5157),
                            PedidoId = 3,
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("DeliverySac.API.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Calle 1 #100, Centro",
                            Nombre = "Café Central"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Avenida Principal 250, Zona Norte",
                            Nombre = "Restaurante El Buen Sabor"
                        },
                        new
                        {
                            Id = 3,
                            Direccion = "Calle Secundaria 75, Barrio Sur",
                            Nombre = "Farmacia Salud Plus"
                        });
                });

            modelBuilder.Entity("DeliverySac.API.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            Descripcion = "2 cafés cortados + 1 medialunas",
                            Estado = 0,
                            FechaActualizacion = new DateTime(2026, 10, 7, 3, 54, 22, 544, DateTimeKind.Utc).AddTicks(5066),
                            FechaCreacion = new DateTime(2026, 10, 7, 3, 54, 22, 544, DateTimeKind.Utc).AddTicks(5066),
                            Monto = 450.00m
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            Descripcion = "Menú completo para 4 personas",
                            Estado = 1,
                            FechaActualizacion = new DateTime(2026, 10, 7, 2, 54, 22, 544, DateTimeKind.Utc).AddTicks(5066),
                            FechaCreacion = new DateTime(2026, 10, 7, 1, 54, 22, 544, DateTimeKind.Utc).AddTicks(5066),
                            Monto = 2500.00m
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 3,
                            Descripcion = "Vitaminas y suplementos varios",
                            Estado = 2,
                            FechaActualizacion = new DateTime(2026, 10, 7, 3, 24, 22, 544, DateTimeKind.Utc).AddTicks(5066),
                            FechaCreacion = new DateTime(2026, 10, 6, 22, 54, 22, 544, DateTimeKind.Utc).AddTicks(5066),
                            Monto = 1800.50m
                        });
                });

            modelBuilder.Entity("DeliverySac.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@deliverysac.com",
                            PasswordHash = "$2a$11$Ynlh8jkdsOFfG1qBJmojZeLDQDMEe3svonSoCc0mCQXZG7hMxyHda",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Email = "repartidor@deliverysac.com",
                            PasswordHash = "$2a$11$9lxJx32N5BMFyS2aiiu.Zeup5LwmGWJZpxe4sjTd0.MvJOBvGjcYa",
                            Rol = "Repartidor"
                        },
                        new
                        {
                            Id = 3,
                            Email = "supervisor@deliverysac.com",
                            PasswordHash = "$2a$11$AK6fS7EAL7PdDCi3O0LOqOIDSLXrNGqpMclpiYjQcG1w9luWHOh.O",
                            Rol = "Supervisor"
                        });
                });

            modelBuilder.Entity("DeliverySac.API.Models.Asignacion", b =>
                {
                    b.HasOne("DeliverySac.API.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliverySac.API.Models.Usuario", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("DeliverySac.API.Models.CambioEstado", b =>
                {
                    b.HasOne("DeliverySac.API.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliverySac.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeliverySac.API.Models.Pedido", b =>
                {
                    b.HasOne("DeliverySac.API.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
