// <auto-generated />
using DeliverySac.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliverySac.API.Migrations
{
    [DbContext(typeof(DeliverySacDbContext))]
    partial class DeliverySacDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeliverySac.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@deliverysac.com",
                            PasswordHash = "$2a$11$z6qMivzjwmP.NSgpYQl48uBKpXWXj77Iog5U6hcFr3uZZTCpMXy8O",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Email = "repartidor@deliverysac.com",
                            PasswordHash = "$2a$11$J2ZUsyBB.1xmVXdaGo9AbORy9lfAuLmwxD0FjU37CldDjM4SPtxSq",
                            Rol = "Repartidor"
                        },
                        new
                        {
                            Id = 3,
                            Email = "supervisor@deliverysac.com",
                            PasswordHash = "$2a$11$umG3cOZqiAqo86ejSGETtuNDWy.J0SvjRlPPp2kAxhtDfAKaqpSSO",
                            Rol = "Supervisor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
